### ISSUE TITLE
file is not present in search results, while it should

### ISSUE THREAD

**Issue by sotto** [tagspaces/tagspaces#1212]
**Describe the bug**
search is unreliable:
file is not present in search results, while it should

**To Reproduce**
1. have a file named in a location "12345678910123456 re 12345678 [tag1].txt"
notice the space between 8 and [
2. using search: search for the word "tag1" in the upper searchbox (above LOCATION)
3. file will not be present in the search results

But when you rename file to "1234567891012345 re 12345678 [tag1].txt" or "12345678910123456 re 1234567 [tag1].txt" and restart tagspaces, and repeat the same search, then it will have the file listed in the search results!

**Expected behavior**
expected to find the file

**Desktop Application:**
 - Operating System: [Windows 10]
 - TagSpaces Version [e.g. 3.6.2]

**Comment by sotto** [comment]
i wrote these tests to see the issue in action: (in my own fork & new branch Issue1212)
https://github.com/sotto/tagspaces/blob/Issue1212/tests/e2e/issue1212.e2e.js

Run them with: 
yarn jest issue1212 --config=jest.config.js

**Comment by uggrock** [comment]
Hi @sotto 
and thanks for your e2e test and bug reporting. We are reworking currently our location index strategy, which I think is the reason for the issue, so the issue should be fixed once we release version 3.7 officially.
Greetings

**Comment by sytolk** [comment]
@sotto I cant repeat this issue with this [PR](https://github.com/tagspaces/tagspaces/pull/1233). Can you run your tests with this PR ?

**Comment by sotto** [comment]
still fails on my machine:  TSTissue1212 - Test Search in file structure: search for files with a specific tag: › TSTissue1212  - Should find 12345678910123456 re 12345678 [tag1].txt when searching for tag1
==> no files are  present in the view when searching for tag1
i tried with merging your PR , and with copying my test-file in the current develop branch
