### ISSUE TITLE
Android-App: Search /Filter not working >No Index

### ISSUE THREAD

**Issue by SuryaLuna** [tagspaces/tagspaces#1712]
Hello,
I wrote several mails to you:
* 17.7.22 to contactus@tagspaces.org
* 4.8.22 to contactus@tagspaces.org, info@tagspaces.org, contact@tagspaces.org
I didn't get an answer to none of them. Why??

My problem:
I have a big problem with the search /filter on Android.
Doesn't matter, what I do, the result is always the same: "Search failed, noindex. No file or folder found."
What I tried:
* Klick on a tag >Show files with this tag.
* Advanced search >Show files with this tag /with at least this tag. With and without re-indexing.
* Manually indexed the folder. Then tried searching like above.
* Closing the app and starting new, with all above tests.
* Removing the folder and adding it again, with all above tests.

Also, when I add /remove a tag from a file, often the app says "renaming the file failed", but it is succesfully renamed (showing the right title + the right tag), also in the file manager it is correct renamed.

My android version is 6.0 (Tablet) and 6.0.1 (Smartphone), my TagSpaces version on both is 4.4.3.
Thanks for help, Bettina

**Comment by uggrock** [comment]
Hi Bettina,
and thanks for reporting this. Maybe your emails went in the spam folders...
I can not reproduce your issue in our test devices. But what I see in your description is that you are using a pretty old Android version. Maybe this is causing your issue.
Greetings,
Ilian

**Comment by SuryaLuna** [comment]
Hi Ilian,
Thanks for your answer :-)
>>pretty old Android version. Maybe this is causing your issue.<< Hm, how disappointing....

I hope, if I have to mail you one time again, my mails do not go for spam anymore now- what is the right adress of these 3?: contactus@tagspaces.org, info@tagspaces.org, contact@tagspaces.org?

Have a nice day, Bettina

**Comment by uggrock** [comment]
We have found and fixed in v5.0.1 a bug which can be causing similar problems, so I am closing this issue for now.

**Comment by SuryaLuna** [comment]
Hello,
I have installed the newest version (5.0.3) on my tablet and my Smartphone, but still the same problem. On both my tablet and my Smartphone I cannot search by tag ("no index found").
On my Smartphone edited files are even not successful saved (but it says "saving successful"). What a pity...

[Bettina - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1s0rbo)	[1s0rbo]

On October 6, 2022 at 7:16 GMT, Ilian ***@***.***> wrote:

We have found and fixed in v5.0.1 a bug which can be causing similar problems, so I am closing this issue for now.

**Comment by uggrock** [comment]
I think we have found and fixed the root cause of the problem. Please try the apk in version 5.0.4 which I just released.

**Comment by SuryaLuna** [comment]
Hello,

yeah, on my tablet the search by tag is now working :-) But...: When I 
open the found files, there is nothing to see in the file. It shows only 
white background, nothing else....

And on my smartphone it is still the same problem- no index found 
 >search by tag not successful. And also still edited files or new ones 
are not saved (but telling me saving was successful).
On both- tablet and smartphone I have now version 5.0.5 installed.



Am 20.10.2022 um 12:42 schrieb Ilian:
