### ISSUE TITLE
OSX version has issues with copy & paste

### ISSUE THREAD

**Issue by Mc128k** [tagspaces/tagspaces#174]
Hi
Again, the OSX version doesn't accept copy/paste via right click or keyboard shortcuts. Also cmd-q is disabled (used to quit).

**Comment by uggrock** [comment]
Fixed in 1.10.x release

**Comment by EntilZha** [comment]
I am running off 1.10.0 and copy paste still doesn't seem to work.

**Comment by uggrock** [comment]
You have to enable the main menu in the settings and then restart TagSpaces. In the next version the menu will be enabled by default on Mac
