### ISSUE TITLE
Duplication of "Files to Proceed" List in Move or Copy Dialog

### ISSUE THREAD

**Issue by binarybum** [tagspaces/tagspaces#210]
1.10.3 on Windows 8.1 64bit:
Have not been able to figure out what causes this yet, but often files are listed twice in the Files to proceed section of the move copy dialog.  Appears to be cosmetic issue only as far as I can tell:

![capture](https://cloud.githubusercontent.com/assets/10375234/6182464/680c1964-b301-11e4-801f-a0aac641c1e2.JPG)

**Comment by binarybum** [comment]
One way to consistently reproduce this behavior (though I suspect there may be other causes as well) is to:
 select checkbox next to file, click on tag already assigned to that file to bring dropdown menu, click directly on move or copy file icon on main toolbar.

This creates a duplicate listing of the file in "Files to proceed" section every time.

**Comment by binarybum** [comment]
just as update - persists 1.11.0

**Comment by uggrock** [comment]
fixed in 2.1.0, try to reproduce please

**Comment by binarybum** [comment]
Persists in 2.1.0.  Please Re-open.  
Still happens sporadically without this method, but consistently reproducible by similar method to that listed above:

Select checkbox next to file. 
Click on tag associated with that file to bring up popup menu.
Now go to hamburger icon (since toolbar is no more) and select copy / move files

![capture dobule file listing](https://cloud.githubusercontent.com/assets/10375234/12698261/418cbd3c-c766-11e5-8722-b5cfb3dddb35.JPG)

**Comment by uggrock** [comment]
fixed in v2.5
