### ISSUE TITLE
Small visual bug when naming a file

### ISSUE THREAD

**Issue by sunjam** [tagspaces/tagspaces#246]
![Imgur example](http://i.imgur.com/FUQWJDm.png)
Always pops up on Windows 7 builds when the file is being created within Tagspaces and often happens when re-naming, but not always.

**Comment by uggrock** [comment]
this is a bug and should be fixed

**Comment by sunjam** [comment]
Bug still present in the current source build of tagspaces and nw.js

**Comment by uggrock** [comment]
UI redesigned -> bug fixed, see pre-release 1.12.2
