### ISSUE TITLE
Crashed on macOS 10.14

### ISSUE THREAD

**Issue by woc2006** [tagspaces/tagspaces#816]
Tagspaces: 3.0.0 - Community
Log:

[crash.log](https://github.com/tagspaces/tagspaces/files/2718468/crash.log)

**Comment by uggrock** [comment]
How does the crash happened?

**Comment by woc2006** [comment]
> How does the crash happened?

press Cmd+Q to close the app

**Comment by uggrock** [comment]
Thanks for clarification. This issue appears to be related to https://github.com/electron/electron/issues/15725 . We will update to the electron version for the next release.

**Comment by uggrock** [comment]
The macOS crashes should be fixed in version [3.0.2](https://github.com/tagspaces/tagspaces/releases/tag/v3.0.2). Can somebody test if this is really the case?

**Comment by uggrock** [comment]
Any feedback on this ?

**Comment by brossetti** [comment]
I can confirm that 3.0.2 is still crashing for me on macOS 10.13.6. Crashes seem to be random, and the app is not running for more than a couple of minutes. My logs look similar to this:

> [atrandomcrash.log](https://github.com/tagspaces/tagspaces/files/2726487/atrandomcrash.log)

**Comment by he2s1he2s2** [comment]
It still crashes when being closed. But it is running stable now.

**Comment by uggrock** [comment]
We updated the quit functionality on Mac and upgraded to Electron 3.1.0 in our new prerelease [3.0.3](https://github.com/tagspaces/tagspaces/releases/tag/v3.0.3). Can somebody please test this issue again on macOS Mojave?

**Comment by woc2006** [comment]
[crash.log](https://github.com/tagspaces/tagspaces/files/2749671/crash.log)
Crash still here.

**Comment by he2s1he2s2** [comment]
Yes,  it still crashes.

**Comment by SierraAmari** [comment]
I installed the app and it immediately crashed. 

[crash log.pdf](https://github.com/tagspaces/tagspaces/files/2815866/crash.log.pdf)

**Comment by alirezavalizade** [comment]
same issue:
Electron: v4
os: Mojave 10.14

```
Logical CPU:     2
Error Code:      0x00000004
Trap Number:     14
```

**Comment by syrabo** [comment]
I installed the app and it immediately crashed (Pro and Free).

macos 10.14.6

Ihttps://github.com/tagspaces/tagspaces/issues/971#issuecomment-515368344

**Comment by uggrock** [comment]
not reproducible on Catalina -> closing
